version: "3"
services:
  notification-service:
    image: 127.0.0.1:8129/xcalibyte/xcal.notification-service:latest
    container_name: dev_rule_service
    ports:
    - "4004:4004"
    networks:
     - agent-test
networks:
    agent-test:
     external: true